---
title: "Analysis scenith data"
author: "Léonard Dubois, Rodrigo Formiga and Harry Sokol"
date: "2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(phyloseq)
#library(microViz)
library(viridis)
library(vegan)
library(ggsignif)
library(rstatix)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)

rm(list = ls())
gc()

colormap_group <- c("#b2df8a", "#a6cee3", "#1f78b4") 
names(colormap_group) <- c("HD", "before_FMT", "after_FMT") 

```


# Import data

```{r}

mpa4_table <- read_tsv(file = "../data/profile_mpa4_vJun23_FMT_Cdiff.tsv", col_names = T, show_col_types = F)
scenith_dt <- read_tsv(file = "../data/scenith_data.tsv", col_names = T, show_col_types = F)
md_mpa4_group <- tibble(sample = colnames(mpa4_table)[-1])
md_mpa4_group <- md_mpa4_group %>% 
    left_join(scenith_dt %>% select(sample, group)) %>% 
    mutate(group = ifelse(is.na(group), "HD", group)) %>% distinct()

rname <- mpa4_table$clade
mpa4_table <- as.matrix(mpa4_table %>% select(-clade))
rownames(mpa4_table) <- rname

mpa4_table_sgb <- mpa4_table[ grepl("t__SGB", rownames(mpa4_table) ), ]
mpa4_table_spc <- mpa4_table[ grepl("s__[A-Za-z_]+$", rownames(mpa4_table) ), ]


pairwise_FMT_dt <- read_tsv(file = "../data/FMT_pairing.tsv", col_names = T, show_col_types = F)
pairwise_FMT_dt_shotgun <- pairwise_FMT_dt %>% filter(data == "shotgun_metagenomics") %>% 
    mutate(FMT_group = paste0("FMT_grp_", row_number())) %>% 
    pivot_longer(cols = c("donor", "before_FMT", "after_FMT"), values_to = "sample")
md_mpa4_group <- md_mpa4_group %>% left_join(pairwise_FMT_dt_shotgun %>% select(sample, FMT_group))

```

Change here to run the chunks below considering Speceis or SGB level

```{r}

mpa4_table_used <- mpa4_table_sgb

```



# Alpha div

```{r}
spec_richness_0_05 <- tibble(sample =  colnames(mpa4_table_used),
                             richness = apply(mpa4_table_used, 2, function(x) sum(x > 0.05))) %>% 
    left_join(md_mpa4_group) %>%
    mutate(group = factor(group, levels = c("HD", "before_FMT", "after_FMT")))


p_alpha <- ggplot(data = spec_richness_0_05, 
       aes(x = group, y = richness, color = group)) + 
    geom_boxplot(outlier.shape = NA) + 
    geom_jitter(height = 0, size = 2) + 
    theme_minimal() +
    ggpubr::stat_compare_means() + 
    ggpubr::stat_pwc( tip.length = 0, p.adjust.method = "BH", hide.ns = T, method = "dunn_test") + 
    scale_color_manual(values = colormap_group) +
    xlab("") + ylab("Species richness (relative abundance>=0.05%)") +
    theme(panel.grid.major.x = element_blank(), 
          legend.position = "none" )

```


# Beta diversity


prepare dist data

```{r}

dt <- mpa4_table_used[ , apply(mpa4_table_used, 2, function(x) max(x) < 95) ]
dt <- dt[rowSums(dt) != 0, ]

# or better  use direct asv relab
dist_beta <- vegdist(t(dt), method = "aitchison", pseudocount = 1e-10)
# Jaccard is also interesting
#dist_beta <- vegdist(t(dt), method = "jaccard", pseudocount = 1e-10)

md <- md_mpa4_group %>% select(sample, group) %>% distinct()
pco_dt <- ecodist::pco(dist_beta)
plot_dt <- as.data.frame(pco_dt$vectors[, 1:2])
plot_dt$sample <- rownames(as.matrix(dist_beta))
plot_dt <- plot_dt %>%  left_join(md)

set.seed(12345)
adonis_res <- adonis2(dist_beta ~ group, data = md, permutations = 1e3)
res_permutest <- permutest(betadisper(d = dist_beta, group = md$group), permutations = 1e3)

p_beta <- plot_dt %>%
    ggplot(data=., aes(x=X1, y=X2) ) + 
    geom_point(size = 2, alpha = 0.9, pch = 21,
               aes(fill = group)) +
    stat_ellipse(aes(color = group)) +
    theme_minimal() + 
    scale_fill_manual(values = colormap_group) + 
    scale_color_manual(values = colormap_group) +
    xlab(paste("PC1", round(100*(pco_dt$values[1] / sum(pco_dt$values)), digits = 2), "%")) + 
    ylab(paste("PC2", round(100*(pco_dt$values[2] / sum(pco_dt$values)), digits = 2), "%")) + 
    #coord_equal() +
    theme(legend.position = "bottom", 
          legend.direction = "horizontal") +
    labs(fill = "", color = "") + 
    # adjust title
    ggtitle("Beta diversity - Aitchison distance", 
            subtitle = paste0("adonis2 R2 = ", as.character(round(adonis_res$R2[1] * 100, 2)),
                              "%;P=", as.character(round(adonis_res$`Pr(>F)`[1], 4)), 
                              " ; permutest P=", as.character(round(res_permutest$tab["Groups", "Pr(>F)"], 4)) ))

```



# Pairwise dist between recipient and donor


```{r}

dist_beta <- vegdist(t(dt), method = "aitchison", pseudocount = 1e-10)
# dist_beta <- vegdist(t(dt), method = "jaccard")

dist_long <- as.matrix(dist_beta) %>%
  as_tibble(rownames = "sample1") %>%
  pivot_longer(-sample1, names_to = "sample2", values_to = "distance") %>%
  filter(sample1 < sample2)

dist_long <- dist_long %>% left_join(pairwise_FMT_dt_shotgun %>% select(sample1 = sample, FMT_group1 = FMT_group, sample_type1 = name)) %>% 
    left_join(pairwise_FMT_dt_shotgun %>% select(sample2 = sample, FMT_group2 = FMT_group, sample_type2 = name)) %>% 
    filter(sample_type1 != "before_FMT", sample_type2 != "before_FMT")

dist_long <- dist_long %>% rowwise() %>% mutate(type_pair = paste(sort(c(sample_type1, sample_type2)), collapse="__")) %>%
    mutate(same_FMT_grp = ifelse(FMT_group1 == FMT_group2, "same_grp", "diff_grp"))



p_donor_ait <- ggplot(data = dist_long %>% filter(type_pair == "after_FMT__donor"), 
       aes(y = distance, x = same_FMT_grp)) + 
    geom_boxplot(outlier.shape = NA) + 
    ggpubr::stat_compare_means(method.args = list(alternative = "greater")) +
    geom_jitter(height = 0, width = 0.3, size = 1.5, alpha = 0.7) + 
    scale_x_discrete(labels=c("diff_grp"="Other donors", "same_grp"="Respective donor")) +
    xlab("") + ylab("Aitchison distance\nAfter FMT samples compared to donors") +
    theme_minimal() + 
    theme(panel.grid.major.x = element_blank())


```



```{r}

cowplot::plot_grid(p_alpha, p_donor_ait, nrow = 1)

```



# Heatmap of composition

Define top species by group
```{r}
TOP_N = 12

rownames(mpa4_table_used) <- rownames(mpa4_table_used) %>% str_remove_all(pattern = ".*s__") %>%
    str_replace_all(pattern = "\\|t__", replacement = " ")

top_spc_grp <- list()
# order is important here to highlights overlap is any
for(grp in c("before_FMT", "HD", "after_FMT")){
    #grp  = "before_FMT"
    tmp <- mpa4_table_used[, md_mpa4_group%>% filter(group == grp) %>% pull(sample)]
    percentile90 <- apply(tmp, 1, function(x) quantile(x, 0.9))
    if(!is.null( unlist(top_spc_grp))){
        percentile90 <- percentile90[!names(percentile90) %in% unlist(top_spc_grp)]
    }
    top_spc <- names(sort(percentile90, decreasing = T))[1:TOP_N]
    top_spc_grp[[grp]] <- top_spc
}

row_split_dt <- rep(paste0("top species ", names(top_spc_grp)), each = TOP_N) 
names(row_split_dt) <- unlist(top_spc_grp)

```



```{r}

relab_dt <- mpa4_table_used[names(row_split_dt), ]
# relab_dt <- relab_dt[apply(mpa4_table_used, 1, function(x) sum(x > 0.05)/ncol(mpa4_table_used)) > 0.4, ]

col_fun_HM <- colorRamp2(c("white", brewer.pal(n = 7, name = "RdYlBu"), "black"),
                         breaks = c(0, 0.01, 0.1, 1, 5, 10, 20, 50, 100))

col_fun_HM <- colorRamp2(c("white", brewer.pal(n = 7, name = "RdYlBu"), "black"),
                         breaks = c(0, 0.001, 0.01, 0.1, 1, 5, 10, 20, 100))

col_split_dt <- md_mpa4_group %>% select(sample, group) %>% distinct() %>% pull(group)
names(col_split_dt) <- md_mpa4_group %>% select(sample, group) %>% distinct() %>% pull(sample)

h <- Heatmap(matrix = relab_dt, 
             col = col_fun_HM,
             
             width = unit(0.35, "cm") * ncol(relab_dt), 
             height = unit(0.35, "cm") * nrow(relab_dt),
             
             row_split = factor(row_split_dt, levels = c("top species before_FMT", "top species HD", "top species after_FMT")),
             
             cluster_rows = T,
             clustering_distance_rows = "spearman", clustering_method_rows = "ward.D2",
             clustering_distance_columns  = "spearman", clustering_method_columns = "ward.D2",

             cluster_columns = T, 
             show_column_names = T, 
             column_split = factor(col_split_dt, levels = c("before_FMT", "HD", "after_FMT")), 
             show_row_dend = F, show_column_dend = F,
             
             cluster_row_slices = FALSE,
             cluster_column_slices = FALSE,
             
             row_title_side = "right",
             row_title_gp = gpar(fontsize = 10),
             column_title_gp = gpar(fontsize = 10),
             border = T,                
             gap = unit(2, "mm"),
             row_names_gp = gpar(fontsize = 8, fontface= "italic"),
             column_names_gp = gpar(fontsize = 8),
             
             rect_gp = gpar(col = "grey", lwd = 0.5),
             show_heatmap_legend =T,
             column_title_side = "bottom", 
             column_title_rot = 0,
             row_names_side = "left", row_dend_side = "right",
             heatmap_legend_param = list(title = "Relative abundance", 
                                         direction = "horizontal", 
                                         title_gp = gpar(fontsize = 10), 
                                         legend_gp = gpar(fontsize = 10),
                                         legend_width = unit(6, "cm"),
                                         break_dist = 1,
                                         at = c(0, 0.01, 0.1, 1, 10, 50, 100)))
draw(h, heatmap_legend_side = "bottom")


```







